language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-vale-static' ]; then cd .. && eval "mv $currentfolder generator-vale-static" && cd generator-vale-static; fi

